### PR TITLE
Add token functionality

### PR DESCRIPTION
**Pull request by lucasprograms**
Adds `token` option and `setToken` method, allowing for authenticated requests to esri.

Also added (& happy to take any of this out)
- `watch` and `prepare` script.
  - `prepare` script  sets up dist directory when using a forked version of this repository
- throwing an error in metadata fetch if esri service returns a response with a non-falsy `error` key (e.g., `{ error: { code: 499, message: "Token required", details: [] } }`)
- not calling `this._projectBounds()` in `_projectBounds()` catch statement if already using the fallback projection endpoint. When I was (mistakenly) appending a token to the fallback projection request, it resulted in endless failed requests to that endpoint

I also want to add:

a) In my private fork of this repo, I have added babel in order to be able to use private classes (e.g., `#map`). The `_map` namespace somehow gets polluted, with very strange results. Changing it to `#map` solves this issue. Generally it looks something like
```js
export default class FeatureService {
  static #fallbackProjectionEndpoint = 'https://tasks.arcgisonline.com/arcgis/rest/services/Geometry/GeometryServer/project';

  #map;
  #maxExtent = [-Infinity, Infinity, -Infinity, Infinity];
  #esriServiceOptions;
  #tileIndices = new Map();
  #featureIndices = new Map();
  #featureCollections = new Map();
  #boundEvent = null;
  #layerId = null;

  serviceMetadata = null;
  ....
```
Adding babel seemed like a pretty major change, and it also seems to require updating the eslint-config from mourner (I at least couldn't get it to work using `babel-eslint` as the parser option.)

Anyhow, if you'd like, I can make a different PR that implements those changes. I've also updated the fork to have the option to disable requests by default, as well as some minor tweaks like checking if requests are enabled in `_clearAndRefreshTiles` before initiating a tile request from there.

b) Thank you again (so much) for this project!!! I had been looking for a solution to this for a while, and when this somehow magically appeared 3 months ago I almost couldn't believe it :)

### CODE REVIEW

**Comment by rowanwins** [comment]
Hey @lucasprograms 

Had a quick scan through and this all looks good, I'll try and get to merging and releasing later this week. 

The babel issue sounds strange. I'm on a new machine from when I wrote the lib so I'll try and install and run from scratch and see what happens. I'd rather not introduce babel, and I can't think of anything in the codebase that should require it...

Cheers

**Comment by lucasprograms** [comment]
Hi @rowanwins, awesome, thank you!

To see the bug in action, update `/docs/src/Map.vue` like so:

add:

```js
data() {
   return { test: null }
},
```

and in `setupLayer` method, add:

```js
this.test = layer;
```

The map style in the browser becomes wonky after that - not totally sure what is going on.

If the `_map` property inside the module is renamed to something beginning with `#`, the issue is resolved. I had to add babel in order to get that private variable syntax to work.

**Comment by rowanwins** [comment]
@lucasprograms it sounds like it could be related to https://github.com/mapbox/mapbox-gl-js/issues/9874

**Comment by lucasprograms** [comment]
> @lucasprograms it sounds like it could be related to [mapbox/mapbox-gl-js#9874](https://github.com/mapbox/mapbox-gl-js/issues/9874)

Oh nice, yeah that looks like the culprit.

**Comment by rowanwins** [comment]
Released as v0.0.2 - thanks @lucasprograms !

**Pull request merged**
